// Channels
const CONNECT_CHANNEL_NAME = 'CONNECT'
const STATS_CHANNEL_NAME = 'STATS'
const QUERIES_CHANNEL_NAME = 'QUERIES'
const ACTIONS_CHANNEL_NAME = 'ACTIONS'
const CLUSTER_CHANNEL_NAME = 'CLUSTER'

module.exports = {
  CONNECT_CHANNEL_NAME,
  CLUSTER_CHANNEL_NAME,
  STATS_CHANNEL_NAME,
  QUERIES_CHANNEL_NAME,
  ACTIONS_CHANNEL_NAME
}
