// Channels
const CONNECT_CHANNEL_NAME = 'CONNECT'
const STATS_CHANNEL_NAME = 'STATS'
const QUERIES_CHANNEL_NAME = 'QUERIES'

module.exports = {
  CONNECT_CHANNEL_NAME,
  STATS_CHANNEL_NAME,
  QUERIES_CHANNEL_NAME
}